version: "3.9"

volumes:
  db-volume:

services:
  server:
    restart: always
    build: .
    container_name: server
    ports:
      - "8090:8090"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true