version: "3.9"

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf
      - ../frontend:/usr/share/nginx/html
    ports: [ '${NGINX_HTTP_PORT}:80' ]
    depends_on: [ gateway ]
    networks: [ backend ]
    restart: always

  gateway:
    build: .
    container_name: gateway
    ports:
      - "8000:8000"
    networks: [backend]
    depends_on: [ ml ]
    restart: always

  ml:
    build: ../ml-service
    container_name: ml
    ports:
      - "8001:8001"
    networks: [ backend ]
    restart: always

networks:
  backend:
    driver: bridge