version: "3.9"

services:

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf
#      - ${NGINX_SSL_CERT_PATH}:/etc/cert.pem
#      - ${NGINX_SSL_KEY_PATH}:/etc/key.pem
      - ../frontend:/usr/share/nginx/html
    ports: ['${NGINX_HTTP_PORT}:80']
    depends_on: [ gateway ]
    networks: [ backend ]
    restart: always

  gateway:
    build: .
    container_name: gateway
    environment: ['CONFIG_PATH=${CONFIG_PATH}']
    networks: [backend]
    depends_on: [ ml ]
    restart: always

  ml:
    build: ../ml-service
    container_name: ml
    networks: [ backend ]
    restart: always

networks:
  backend:
    driver: bridge