version: "3.9"

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf
      - ${NGINX_SSL_CERT_PATH}:/etc/cert.pem
      - ${NGINX_SSL_KEY_PATH}:/etc/key.pem
      - ./dist:/usr/share/nginx/html
    ports: ['${NGINX_HTTP_PORT}:80', '${NGINX_HTTPS_PORT}:443']
    depends_on: [ backend ]
    networks: [ backend ]
    restart: always
  backend:
    build: .
    container_name: backend
    environment: ['CONFIG_PATH=${CONFIG_PATH}']
    networks: [backend]
    restart: always

networks:
  backend:
    driver: bridge