env: prod
log_level: info

http_server:
  host: cluster-text.ru
  port: 8000
  read_timeout: 5s
  write_timeout: 5s
  swagger_enabled: true #TODO: когда выйдем в прод не забыть убрать

ml_client:
  port: 8001
  host: ml
  timeout: 5s
  circuit_breaker:
    half_open_max_successes: 10
    min_threshold: 10
    failure_rate: 0.4
    counter_reset_interval: 10s