env: local
log_level: debug

http_server:
  host: localhost
  port: 8000
  read_timeout: 5s
  write_timeout: 5s
  swagger_enabled: true

ml_client:
  port: 8001
  host: ml
  timeout: 5s
  circuit_breaker:
    half_open_max_successes: 10
    min_threshold: 10
    failure_rate: 0.4
    counter_reset_interval: 10s

