name: Docker Compose Actions Workflow
on:
  push:
    branches: [master]

  release:
    runs-on: ubuntu-latest
    steps:
      - name: pull project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            cd ./text-markup/gateway/
            sudo make stop
            sudo docker rmi $(sudo docker images -a | grep ${{ secrets.DOCKER_USER }} | awk '{print $3}')
            sudo docker pull ${{ secrets.DOCKER_USER }}/server
            sudo docker pull ${{ secrets.DOCKER_USER }}/ml
      - name: run project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git pull --progress
            make start