name: Deploy Workflow
on:
  workflow_dispatch:
      environment:
        description: 'Environment to run deploy (no envs now)'
        type: environment
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: run project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ./text-markup/gateway/
            git restore .
            git pull --progress
            sudo make prod-start