name: Gateway Workflow
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          cd ./ml-service
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/ml:latest -f ./Dockerfile .
          cd ..
      - name: Push the image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ml --all-tags